/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PayrollSystem;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael Tipon-tipon
 */
public class JFrame6 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame6
     */
    public JFrame6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        birnumTxt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pagnumTxt = new javax.swing.JTextField();
        enumbTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        enameTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        birTxt = new javax.swing.JTextField();
        sssnumTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bdayTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radMale = new javax.swing.JRadioButton();
        radFem = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pnTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radFt = new javax.swing.JRadioButton();
        radPt = new javax.swing.JRadioButton();
        PAss = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cPass = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cnclBtn1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        birnumTxt.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create Account");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("PAG-IBIG Number");

        enumbTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enumbTxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Employee Number");

        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 102, 153));
        saveBtn.setText("Save");
        saveBtn.setActionCommand("");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        enameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameTxtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BIR Number");

        birTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birTxtActionPerformed(evt);
            }
        });

        sssnumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssnumTxtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Employee Name");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SSS Number");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender");

        bdayTxt.setForeground(new java.awt.Color(153, 153, 153));
        bdayTxt.setText("YYY-MM-DD (2009/02/17)");
        bdayTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bdayTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bdayTxtFocusLost(evt);
            }
        });
        bdayTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayTxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Birthdate");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Basic Info");

        radMale.setForeground(new java.awt.Color(204, 204, 204));
        radMale.setText("Male");
        radMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radMaleMouseClicked(evt);
            }
        });
        radMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMaleActionPerformed(evt);
            }
        });

        radFem.setForeground(new java.awt.Color(204, 204, 204));
        radFem.setText("Female");
        radFem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radFemMouseClicked(evt);
            }
        });
        radFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFemActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Phone Number");

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Info");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Employment Status");

        radFt.setForeground(new java.awt.Color(255, 255, 255));
        radFt.setText("Fulltime");
        radFt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFtActionPerformed(evt);
            }
        });

        radPt.setForeground(new java.awt.Color(255, 255, 255));
        radPt.setText("Part-Time");

        PAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAssActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password");

        cPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPassActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Confirm Password");

        cnclBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cnclBtn1.setForeground(new java.awt.Color(0, 102, 153));
        cnclBtn1.setText("Cancel");
        cnclBtn1.setActionCommand("");
        cnclBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout birnumTxtLayout = new javax.swing.GroupLayout(birnumTxt);
        birnumTxt.setLayout(birnumTxtLayout);
        birnumTxtLayout.setHorizontalGroup(
            birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, birnumTxtLayout.createSequentialGroup()
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, birnumTxtLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, birnumTxtLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(birnumTxtLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enumbTxt))
                            .addGroup(birnumTxtLayout.createSequentialGroup()
                                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel17))
                                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(birnumTxtLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radFem, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(birnumTxtLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(bdayTxt))
                                    .addGroup(birnumTxtLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(enameTxt))))
                            .addGroup(birnumTxtLayout.createSequentialGroup()
                                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnTxt)
                                    .addComponent(emailTxt)))
                            .addGroup(birnumTxtLayout.createSequentialGroup()
                                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pagnumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(birTxt)))
                            .addComponent(sssnumTxt)
                            .addGroup(birnumTxtLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radFt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radPt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addComponent(PAss)
                            .addComponent(jLabel15)
                            .addComponent(cPass)
                            .addComponent(jLabel21))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, birnumTxtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cnclBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        birnumTxtLayout.setVerticalGroup(
            birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(birnumTxtLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enumbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(radMale)
                    .addComponent(radFem))
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(radFt)
                    .addComponent(radPt))
                .addGap(18, 18, 18)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(birnumTxtLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagnumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(birnumTxtLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sssnumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(birnumTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cnclBtn1))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(birnumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(birnumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void birTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birTxtActionPerformed

    private void sssnumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssnumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssnumTxtActionPerformed

    private void radFtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radFtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
     try {
    String password = PAss.getText().trim();
    String confirmPassword = cPass.getText().trim();

    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(null, "Passwords do not match! Please try again.");
        return;
    }

    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(
        "jdbc:mysql://127.0.0.1:3306/teachers_payroll?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC", 
        "root", "BSCS2ndyear"
    );

    // Insert into employees table (WITH password)
    String employeeQuery = "INSERT INTO employees (employee_name, employee_number, birthdate, gender, email, phone_number, employment_status, pag_ibig_number, bir_number, sss_number, password) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement empPst = con.prepareStatement(employeeQuery);
    empPst.setString(1, enameTxt.getText());
    empPst.setString(2, enumbTxt.getText());
    empPst.setString(3, bdayTxt.getText());
    empPst.setString(4, radMale.isSelected() ? "Male" : "Female");
    empPst.setString(5, emailTxt.getText());
    empPst.setString(6, pnTxt.getText());
    empPst.setString(7, radFt.isSelected() ? "Full-Time" : "Part-Time");
    empPst.setString(8, pagnumTxt.getText());
    empPst.setString(9, birTxt.getText());
    empPst.setString(10, sssnumTxt.getText());
    empPst.setString(11, password); // Store password in employees table

    int rowsInsertedEmp = empPst.executeUpdate();

    // Insert into login table (password must match)
    String loginQuery = "INSERT INTO login (employee_number, password) VALUES (?, ?)";
    PreparedStatement loginPst = con.prepareStatement(loginQuery);
    loginPst.setString(1, enumbTxt.getText()); 
    loginPst.setString(2, password); 

    int rowsInsertedLogin = loginPst.executeUpdate();

    if (rowsInsertedEmp > 0 && rowsInsertedLogin > 0) {
        JOptionPane.showMessageDialog(null, "Account Created Successfully!");
        JFrame1 frame = new JFrame1();
        frame.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Failed to Create Account.");
    }

    // Close connections
    empPst.close();
    loginPst.close();
    con.close();
} catch (ClassNotFoundException e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    e.printStackTrace();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    e.printStackTrace();
}

            
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        


 
    }//GEN-LAST:event_saveBtnActionPerformed

    private void enameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameTxtActionPerformed

    private void PAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAssActionPerformed

    private void cPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPassActionPerformed

    private void cnclBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclBtn1ActionPerformed
          JFrame1 nf = new JFrame1  ();
                  nf.setVisible(true);
                  this.dispose();
                          
    }//GEN-LAST:event_cnclBtn1ActionPerformed

    private void enumbTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enumbTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enumbTxtActionPerformed

    private void bdayTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bdayTxtFocusGained
         if(bdayTxt.getText().equals("YEAR-MONTH-DAY"))
         {
         bdayTxt.setText("");
          bdayTxt.setForeground(new Color(0,0,0));
         }
        
        
    }//GEN-LAST:event_bdayTxtFocusGained

    private void bdayTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bdayTxtFocusLost
        // TODO add your handling code here:
        if(bdayTxt.getText().equals("YYY-MM-DD (2009/02/17) " ))
         {
         bdayTxt.setText("");
          bdayTxt.setForeground(new Color(153,153,153,153));
         }
    }//GEN-LAST:event_bdayTxtFocusLost

    private void bdayTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdayTxtActionPerformed

    private void radMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMaleActionPerformed
        radMale.setForeground(Color.GRAY);
        radFem.setForeground(Color.GRAY);
        radMale.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent evt) {
        if (radMale.isSelected()) {  
            radMale.setForeground(Color.BLACK);    
            radFem.setForeground(Color.GRAY);  
            radFem.setSelected(false);          
        } else {
            radMale.setForeground(Color.GRAY);     
        }
    }
});
   
    }//GEN-LAST:event_radMaleActionPerformed

    private void radMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radMaleMouseClicked



    }//GEN-LAST:event_radMaleMouseClicked

    private void radFemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radFemMouseClicked
        // TODO add your handling code here:
      

    }//GEN-LAST:event_radFemMouseClicked

    private void radFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFemActionPerformed
        // TODO add your handling code here:
        radMale.setForeground(Color.GRAY);
        radFem.setForeground(Color.GRAY);
        
        
   radFem.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent evt) {
        if (radFem.isSelected()) {  // If radFemale is clicked
            radFem.setForeground(Color.BLACK);  // Set female to selected color
            radMale.setForeground(Color.GRAY);     // Set male to unselected color
            radMale.setSelected(false);            // Deselect male
        } else {
            radFem.setForeground(Color.GRAY);   // Reset female to unselected color
        }
    }
});
    }//GEN-LAST:event_radFemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PAss;
    private javax.swing.JTextField bdayTxt;
    private javax.swing.JTextField birTxt;
    private javax.swing.JPanel birnumTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cPass;
    private javax.swing.JButton cnclBtn1;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField enameTxt;
    private javax.swing.JTextField enumbTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pagnumTxt;
    private javax.swing.JTextField pnTxt;
    private javax.swing.JRadioButton radFem;
    private javax.swing.JRadioButton radFt;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JRadioButton radPt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField sssnumTxt;
    // End of variables declaration//GEN-END:variables
}
